# Generated by Django 3.1.4 on 2020-12-16 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Nombre del usuario', max_length=100)),
                ('lastName', models.CharField(help_text='Apellido del usuario', max_length=100)),
                ('date', models.DateField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Creación')),
                ('dateUpdated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(help_text='Contraseña del usuario', max_length=100)),
                ('tipo', models.CharField(default='CLIENTE', help_text='Tipo de Usuario', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
