# Generated by Django 3.1.4 on 2020-12-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201218_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(default='CLIENTE', help_text='Tipo de Usuario', max_length=100),
        ),
    ]
