# Generated by Django 3.1.4 on 2020-12-25 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201218_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('access', models.CharField(help_text='Token de acceso', max_length=256, primary_key=True, serialize=False, unique=True)),
                ('refresh', models.CharField(blank=True, help_text='Refresh Token', max_length=256, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Creación')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
